# Generated by Django 5.2 on 2025-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('place_address', models.CharField(blank=True, max_length=255, null=True)),
                ('place_description', models.TextField()),
                ('place_image', models.BinaryField()),
            ],
        ),
    ]
