# Generated by Django 5.2 on 2025-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialLinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officiallink',
            name='bg_image',
            field=models.BinaryField(),
        ),
    ]
